### ISSUE TITLE
Mishandled user authentication for JWT local storage.

### ISSUE THREAD

**Issue by ChennyChicken** [Hyper-Devs/Hyper-Devs#190]
https://github.com/Hyper-Devs/Hyper-Devs/blame/1d4636edbd4270d45f1877998eb7669c96fdae69/client/src/Components/IsAuthenticated.jsx#L20

```javascript
  useEffect(()=>{if (user === null) {
    setTitleModal("Unauthorized Access.");
    setBodyModal("Please Login to access the page!")
    setShowModal(true)
  }
```

This block of code does not check if a user exists in the database or not. It is possible to copy a legitimate JWT value and modify it to allow logging in without proper credentials.

Here's a sample decoded JWT with its encoded string.
```json
{
  "userId": 6969,
  "name": "Chinese Chicken",
  "AccessID": 6969,
  "position": "Bird",
  "role": "Admin",
  "iat": 1685990758
}
```

```jwt
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY5NjksIm5hbWUiOiJDaGluZXNlIENoaWNrZW4iLCJBY2Nlc3NJRCI6Njk2OSwicG9zaXRpb24iOiJCaXJkIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjg1OTkwNzU4fQ.lBEWATPQyoHQZrV9By9AGzIBj-16-meDSbO8dTisXsI
```

![image](https://github.com/Hyper-Devs/Hyper-Devs/assets/123671505/9d081ca6-cc34-4231-acf4-ec18ede9484b)

This user does not exist yet it allowed me to access the admin panel.

~~hello may plus points ba if mag crossover ang groups, please say yes~~

**Comment by biploop** [comment]
Na finish nani nimo @MattRadars ?
